"""
This type stub file was generated by pyright.
"""

import collections
import os

import numpy as np
from dm_control import composer, mjcf
from dm_control.composer import define
from dm_control.composer.observation import observable

"""A 2x4 Duplo brick."""
_DUPLO_XML_PATH = ...
_StudSize = ...
_StudParams = ...
_STUD_SIZE_PARAMS = ...
_COLOR_NOT_BETWEEN_0_AND_1 = ...

class Duplo(composer.Entity):
    """A 2x4 Duplo brick."""

    def initialize_episode_mjcf(self, random_state):  # -> None:
        """Randomizes the stud radius (and therefore the separation force)."""
        ...
    @property
    def studs(self):  # -> ndarray[Unknown, Unknown]:
        """A (2, 4) numpy array of `mjcf.Elements` corresponding to stud sites."""
        ...
    @property
    def holes(self):  # -> ndarray[Unknown, Unknown]:
        """A (2, 4) numpy array of `mjcf.Elements` corresponding to hole sites."""
        ...
    @property
    def mjcf_model(self):  # -> RootElement:
        ...

class DuploObservables(composer.Observables, composer.FreePropObservableMixin):
    """Observables for the `Duplo` prop."""

    @define.observable
    def position(self):  # -> MJCFFeature:
        ...
    @define.observable
    def orientation(self):  # -> MJCFFeature:
        ...
    @define.observable
    def linear_velocity(self):  # -> MJCFFeature:
        ...
    @define.observable
    def angular_velocity(self):  # -> MJCFFeature:
        ...
    @define.observable
    def force(self):  # -> MJCFFeature:
        ...
