"""
This type stub file was generated by pyright.
"""

import glfw

"""An OpenGL context created via GLFW."""

class GLContext:
    """An OpenGL context created via GLFW."""

    def __init__(self, max_width, max_height) -> None: ...
    def make_current(self):  # -> None:
        ...
    def free(self):  # -> None:
        ...
    def __del__(self):  # -> None:
        ...
