"""
This type stub file was generated by pyright.
"""

from .. import exceptions
from .notebook import in_notebook, scene_to_html, scene_to_notebook
from .widget import SceneWidget
from .windowed import SceneViewer, render_scene

"""
viewer
-------------

View meshes and scenes via pyglet or inline HTML.
"""
__all__ = ["SceneWidget", "SceneViewer", "render_scene", "in_notebook", "scene_to_notebook", "scene_to_html"]
