"""
This type stub file was generated by pyright.
"""

from . import (
    boolean,
    caching,
    collision,
    comparison,
    convex,
    creation,
    curvature,
    decomposition,
    geometry,
    graph,
    grouping,
    inertia,
    intersections,
    path,
    permutate,
    poses,
    primitives,
    proximity,
    ray,
    registration,
    remesh,
    repair,
    sample,
    smoothing,
    transformations,
    triangles,
    units,
    util,
)
from .base import Trimesh
from .constants import tol
from .exchange.load import available_formats, load, load_mesh, load_path, load_remote
from .points import PointCloud
from .scene.scene import Scene
from .transformations import transform_points
from .util import unitize
from .version import __version__

"""
https://github.com/mikedh/trimesh
------------------------------------

Trimesh is a pure Python (2.7- 3.3+) library for loading and using triangular
meshes with an emphasis on watertight meshes. The goal of the library is to
provide a fully featured Trimesh object which allows for easy manipulation
and analysis, in the style of the Polygon object in the Shapely library.
"""
__all__ = [
    "PointCloud",
    "Trimesh",
    "Scene",
    "util",
    "__version__",
    "available_formats",
    "boolean",
    "bounds",
    "caching",
    "collision",
    "comparison",
    "convex",
    "creation",
    "curvature",
    "decomposition",
    "geometry",
    "graph",
    "grouping",
    "inertia",
    "intersections",
    "load",
    "load_mesh",
    "load_path",
    "load_remote",
    "nsphere",
    "path",
    "permutate",
    "poses",
    "primitives",
    "proximity",
    "ray",
    "registration",
    "remesh",
    "repair",
    "sample",
    "smoothing",
    "tol",
    "transform_points",
    "transformations",
    "triangles",
    "unitize",
    "units",
    "utilScene",
    "voxel",
]
