"""
This type stub file was generated by pyright.
"""

"""
schemas.py
-------------

Tools for dealing with schemas, particularly JSONschema
"""

def resolve(item, resolver):  # -> list[Unknown] | dict[Unknown, Unknown]:
    """
    Given a JSON Schema containing `$ref` keys recursively
    evaluate to find and replace referenced files with their
    actual values using trimesh.resolvers.Resolver objects.

    Parameters
    ---------------
    item : any
      JSON schema including `$ref` to other files
    resolver : trimesh.visual.resolver.Resolver
      Resolver to fetch referenced assets

    Returns
    ----------
    result : any
      JSONSchema with references replaced
    """
    ...
