"""
This type stub file was generated by pyright.
"""

"""
# version.py

Get the current version from package metadata or pyproject.toml
if everything else fails.
"""
__version__ = ...
if __name__ == "__main__": ...
