"""
This type stub file was generated by pyright.
"""

from dm_control.composer import entity as entity_module

"""The base empty arena that defines global settings for Composer."""
_ARENA_XML_PATH = ...

class Arena(entity_module.Entity):
    """The base empty arena that defines global settings for Composer."""

    def __init__(self, *args, **kwargs) -> None: ...
    def add_free_entity(self, entity):
        """Includes an entity in the arena as a free-moving body."""
        ...
    @property
    def mjcf_model(self):  # -> RootElement | None:
        ...
