_target_: ahac.AHAC
_recursive_: False
actor_config:
  _target_: ahac_utils_model.actor.ActorDeterministicMLP # ahac_utils_model.actor.ActorStochasticMLP
  units: ${resolve_child:[64,64],${env.shac.actor_mlp},units}
  activation: elu
critic_config:
  _target_: ahac_utils_model.critic.DoubleCriticMLP
  units: ${resolve_child:[64,64],${env.shac.critic_mlp},units}
  activation: elu
actor_lr: ${resolve_child:2e-3,${env.shac},actor_lr}
critic_lr: ${resolve_child:2e-3,${env.shac},critic_lr}
lambd_lr: 5e-4
contact_threshold: 500
lr_schedule: linear
obs_rms: False
ret_rms: False
critic_iterations: # if not specified will do early stopping
critic_batches: 4
critic_method: one-step #td-lambda # ('td-lambda', 'one-step')
lam: 0.95
gamma: 0.99
max_epochs: ${resolve_child:2000,${env.shac},max_epochs}
steps_min: 8
steps_max: 64
grad_norm: 1.0
save_interval: ${resolve_child:400,${env.shac},save_interval}
stochastic_eval: False
eval_runs: 12
train: ${general.train}
device: ${general.device}