"""
This type stub file was generated by pyright.
"""

import ctypes
import os
from ctypes import POINTER, Structure, c_bool, c_char_p, c_double, c_int, c_uint, c_uint64, c_void_p

import numpy as np
import trimesh

_lib_files = ...

class CoACD_Mesh(ctypes.Structure):
    _fields_ = ...

class CoACD_MeshArray(ctypes.Structure):
    _fields_ = ...

class Mesh:
    def __init__(self, vertices=..., indices=...) -> None: ...

def run_coacd(
    mesh: Mesh,
    threshold: float = ...,
    max_convex_hull: int = ...,
    preprocess_mode: str = ...,
    preprocess_resolution: int = ...,
    resolution: int = ...,
    mcts_nodes: int = ...,
    mcts_iterations: int = ...,
    mcts_max_depth: int = ...,
    pca: int = ...,
    merge: bool = ...,
    seed: int = ...,
):  # -> list[Unknown]:
    ...

def set_log_level(level: str):  # -> None:
    ...

if __name__ == "__main__":
    mesh = ...
    mesh = ...
    result = ...
    mesh_parts = ...
    scene = ...
