"""
This type stub file was generated by pyright.
"""

from dm_control.viewer import application

"""Suite environments viewer package."""

def launch(environment_loader, policy=..., title=..., width=..., height=...):  # -> None:
    """Launches an environment viewer.

    Args:
      environment_loader: An environment loader (a callable that returns an
        instance of dm_control.rl.control.Environment), an instance of
        dm_control.rl.control.Environment.
      policy: An optional callable corresponding to a policy to execute within the
        environment. It should accept a `TimeStep` and return a numpy array of
        actions conforming to the output of `environment.action_spec()`.
      title: Application title to be displayed in the title bar.
      width: Window width, in pixels.
      height: Window height, in pixels.
    Raises:
        ValueError: When 'environment_loader' argument is set to None.
    """
    ...
