"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
_SYSTEM = ...
_MUJOCO_GL = ...
if _MUJOCO_GL not in ("disable", "disabled", "off", "false", "0"):
    _VALID_MUJOCO_GL = ...
