"""
This type stub file was generated by pyright.
"""

from absl.testing import absltest

"""Tests for msh2obj.py."""
_MESH_FIELDS = ...
_XML = ...

class MshTest(absltest.TestCase):
    def test_obj_model_matches_msh_model(self) -> None: ...

if __name__ == "__main__": ...
