"""
This type stub file was generated by pyright.
"""

"""Roll out open-loop trajectories from initial states, get subsequent states and sensor values."""

def rollout(
    model,
    data,
    initial_state=...,
    ctrl=...,
    *,
    skip_checks=...,
    nstate=...,
    nstep=...,
    initial_time=...,
    initial_warmstart=...,
    qfrc_applied=...,
    xfrc_applied=...,
    mocap=...,
    state=...,
    sensordata=...,
):  # -> tuple[Unknown | None, Unknown | None] | tuple[ndarray[Any, dtype[float64]], ndarray[Any, dtype[float64]]]:
    """Roll out open-loop trajectories from initial states, get subsequent states and sensor values.

    This function serves as a Python wrapper for the C++ functionality in
    `rollout.cc`, please see documentation therein. This python funtion will
    infer `nstate` and `nstep`, tile input arguments with singleton dimensions,
    and allocate output arguments if none are given.
    """
    ...
