"""
This type stub file was generated by pyright.
"""

from .. import constants

@constants.log_time
def contains_points(intersector, points, check_direction=...):  # -> NDArray[Any]:
    """
    Check if a mesh contains a set of points, using ray tests.

    If the point is on the surface of the mesh, behavior is
    undefined.

    Parameters
    ---------
    mesh: Trimesh object
    points: (n,3) points in space

    Returns
    ---------
    contains : (n) bool
                  Whether point is inside mesh or not
    """
    ...
