"""
This type stub file was generated by pyright.
"""

import atexit
import ctypes
import os

from mujoco.cgl import cgl

"""An Apple CGL context for offscreen rendering on macOS."""
_ATTRIB = cgl.CGLPixelFormatAttribute
_PROFILE = cgl.CGLOpenGLProfile

class GLContext:
    """An EGL context for headless accelerated OpenGL rendering on GPU devices."""

    def __init__(self, max_width, max_height) -> None: ...
    def make_current(self):  # -> None:
        ...
    def free(self):  # -> None:
        """Frees resources associated with this context."""
        ...
    def __del__(self):  # -> None:
        ...
