"""
This type stub file was generated by pyright.
"""

import os

from dm_control.utils import io as resources

"""Functions to manage the common assets for domains."""
_SUITE_DIR = ...
_FILENAMES = ...
ASSETS = ...

def read_model(model_filename):  # -> Any:
    """Reads a model XML file and returns its contents as a string."""
    ...
