"""
This type stub file was generated by pyright.
"""

from dm_control import composer
from dm_control.composer import define
from dm_control.composer.observation import observable

"""Prop consisting of a single geom with position and velocity sensors."""

class Primitive(composer.Entity):
    """A prop consisting of a single geom with position and velocity sensors."""

    @property
    def geom(self):
        """The geom belonging to this prop."""
        ...
    @property
    def position(self):
        """Sensor that returns the prop position."""
        ...
    @property
    def orientation(self):
        """Sensor that returns the prop orientation (as a quaternion)."""
        ...
    @property
    def linear_velocity(self):
        """Sensor that returns the linear velocity of the prop."""
        ...
    @property
    def angular_velocity(self):
        """Sensor that returns the angular velocity of the prop."""
        ...
    @property
    def mjcf_model(self): ...

class PrimitiveObservables(composer.Observables, composer.FreePropObservableMixin):
    """Primitive entity's observables."""

    @define.observable
    def position(self):  # -> MJCFFeature:
        ...
    @define.observable
    def orientation(self):  # -> MJCFFeature:
        ...
    @define.observable
    def linear_velocity(self):  # -> MJCFFeature:
        ...
    @define.observable
    def angular_velocity(self):  # -> MJCFFeature:
        ...
