"""
This type stub file was generated by pyright.
"""

import collections
import os

from absl import logging
from dm_control._render import constants

"""OpenGL context management for rendering MuJoCo scenes.

By default, the `Renderer` class will try to load one of the following rendering
APIs, in descending order of priority: GLFW > EGL > OSMesa.

It is also possible to select a specific backend by setting the `MUJOCO_GL=`
environment variable to 'glfw', 'egl', or 'osmesa'.
"""
BACKEND = ...
_ALL_RENDERERS = ...
_NO_RENDERER = ...
if BACKEND is not None:
    import_func = ...
    Renderer = ...
else: ...
USING_GPU = ...
