"""
This type stub file was generated by pyright.
"""

from .. import resolvers
from . import color, material, objects, texture
from .color import (
    DEFAULT_COLOR,
    ColorVisuals,
    interpolate,
    linear_color_map,
    random_color,
    to_rgba,
    uv_to_color,
    uv_to_interpolated_color,
)
from .objects import concatenate, create_visual
from .texture import TextureVisuals

"""
visual
-------------

Handle visual properties for meshes, including color and texture
"""
__all__ = [
    "color",
    "texture",
    "resolvers",
    "TextureVisuals",
    "ColorVisuals",
    "random_color",
    "to_rgba",
    "create_visual",
    "DEFAULT_COLOR",
    "interpolate",
    "linear_color_map",
    "uv_to_color",
    "uv_to_interpolated_color",
]
