"""
This type stub file was generated by pyright.
"""

from dm_control import _render
from dm_control.viewer.gui import glfw_gui

"""Viewer's windowing systems."""
RenderWindow = ...
RenderWindow = ...
if RenderWindow is None:
    def ErrorRenderWindow(*args, **kwargs): ...

    RenderWindow = ...
