"""
This type stub file was generated by pyright.
"""

import numpy as np

"""OpenGL utility for rendering numpy arrays as images on a quad surface."""
_FULLSCREEN_QUAD_VERTEX_POSITONS_AND_TEXTURE_COORDS = np.array(
    [-1, -1, 0, 1, -1, 1, 0, 0, 1, -1, 1, 1, 1, 1, 1, 0], dtype=np.float32
)
_FLOATS_PER_XY = ...
_FLOATS_PER_VERTEX = ...
_SIZE_OF_FLOAT = ...
_VERTEX_SHADER = ...
_FRAGMENT_SHADER = ...
_VAR_POSITION = ...
_VAR_UV = ...
_VAR_TEXTURE_SAMPLER = ...

class FullscreenQuadRenderer:
    """Renders pixmaps on a fullscreen quad using OpenGL."""

    def __init__(self) -> None:
        """Initializes the fullscreen quad renderer."""
        ...
    def render(self, pixmap, viewport_shape):  # -> None:
        """Renders the pixmap on a fullscreen quad.

        Args:
          pixmap: A 3D numpy array of bytes (np.uint8), with dimensions
            (width, height, 3).
          viewport_shape: A tuple of two elements, (width, height).
        """
        ...
