"""
This type stub file was generated by pyright.
"""

from dm_control import mujoco
from dm_control.suite import base

"""Cheetah Domain."""
_DEFAULT_TIME_LIMIT = ...
_RUN_SPEED = ...
SUITE = ...

def get_model_and_assets():  # -> tuple[Any, dict[str, Any]]:
    """Returns a tuple containing the model XML string and a dict of assets."""
    ...

@SUITE.add("benchmarking")
def run(time_limit=..., random=..., environment_kwargs=...):  # -> Environment:
    """Returns the run task."""
    ...

class Physics(mujoco.Physics):
    """Physics simulation with additional features for the Cheetah domain."""

    def speed(self):
        """Returns the horizontal speed of the Cheetah."""
        ...

class Cheetah(base.Task):
    """A `Task` to train a running Cheetah."""

    def initialize_episode(self, physics):  # -> None:
        """Sets the state of the environment at the start of each episode."""
        ...
    def get_observation(self, physics):  # -> OrderedDict[Unknown, Unknown]:
        """Returns an observation of the state, ignoring horizontal position."""
        ...
    def get_reward(self, physics):  # -> float | NDArray[Any]:
        """Returns a reward to the agent."""
        ...
