"""
This type stub file was generated by pyright.
"""

from mujoco.mjx._src.collision_base import Contact, GeomInfo

"""Collision primitives."""

def plane_sphere(plane: GeomInfo, sphere: GeomInfo) -> Contact:
    """Calculates contact between a plane and a sphere."""
    ...

def plane_capsule(plane: GeomInfo, cap: GeomInfo) -> Contact:
    """Calculates two contacts between a capsule and a plane."""
    ...

def sphere_sphere(s1: GeomInfo, s2: GeomInfo) -> Contact:
    """Calculates contact between two spheres."""
    ...

def sphere_capsule(sphere: GeomInfo, cap: GeomInfo) -> Contact:
    """Calculates one contact between a sphere and a capsule."""
    ...

def capsule_capsule(cap1: GeomInfo, cap2: GeomInfo) -> Contact:
    """Calculates one contact between two capsules."""
    ...
