"""
This type stub file was generated by pyright.
"""

from mujoco.mjx._src.types import Data, Model

"""
This type stub file was generated by pyright.
"""

def make_data(m: Model) -> Data:
    """Allocate and initialize Data."""
    ...
