"""
This type stub file was generated by pyright.
"""

from typing import Tuple

import jax
from mujoco.mjx._src.types import Data, Model

"""Engine support functions."""

def jac(m: Model, d: Data, point: jax.Array, body_id: jax.Array) -> Tuple[jax.Array, jax.Array]:
    """Compute pair of (NV, 3) Jacobians of global point attached to body."""
    ...

def jac_dif_pair(m: Model, d: Data, pos: jax.Array, body_1: jax.Array, body_2: jax.Array) -> jax.Array:
    """Compute Jacobian difference for two body points."""
    ...

def apply_ft(m: Model, d: Data, force: jax.Array, torque: jax.Array, point: jax.Array, body_id: jax.Array) -> jax.Array:
    """Apply Cartesian force and torque."""
    ...

def xfrc_accumulate(m: Model, d: Data) -> jax.Array:
    """Accumulate xfrc_applied into a qfrc."""
    ...
