"""
This type stub file was generated by pyright.
"""

"""Tools for adding custom cameras to the arena."""
CameraSpec = ...
FRONT_CLOSE = ...
FRONT_FAR = ...
TOP_DOWN = ...
LEFT_CLOSE = ...
RIGHT_CLOSE = ...

def add_camera_observables(entity, obs_settings, *camera_specs):  # -> OrderedDict[Unknown, Unknown]:
    """Adds cameras to an entity's worldbody and configures observables for them.

    Args:
      entity: A `composer.Entity`.
      obs_settings: An `observations.ObservationSettings` instance.
      *camera_specs: Instances of `CameraSpec`.

    Returns:
      A `collections.OrderedDict` keyed on camera names, containing pre-configured
      `observable.MJCFCamera` instances.
    """
    ...
