"""
This type stub file was generated by pyright.
"""

"""Custom robot constructors with manipulation-specific defaults."""
ARM_OFFSET = ...

def make_arm(obs_settings):  # -> JacoArm:
    """Constructs a robot arm with manipulation-specific defaults.

    Args:
      obs_settings: `observations.ObservationSettings` instance.

    Returns:
      An instance of `manipulators.base.RobotArm`.
    """
    ...

def make_hand(obs_settings):  # -> JacoHand:
    """Constructs a robot hand with manipulation-specific defaults.

    Args:
      obs_settings: `observations.ObservationSettings` instance.

    Returns:
      An instance of `manipulators.base.RobotHand`.
    """
    ...
