"""
This type stub file was generated by pyright.
"""

def load_xyz(file_obj, delimiter=..., **kwargs):  # -> dict[str, Unknown]:
    """
    Load an XYZ file into a PointCloud.

    Parameters
    ------------
    file_obj : an open file-like object
      Source data, ASCII XYZ
    delimiter : None or string
      Characters used to separate the columns of the file
      If not passed will use whitespace or commas

    Returns
    ----------
    kwargs : dict
      Data which can be passed to PointCloud constructor
    """
    ...

def export_xyz(cloud, write_colors=..., delimiter=...):  # -> str:
    """
    Export a PointCloud object to an XYZ format string.

    Parameters
    -------------
    cloud : trimesh.PointCloud
      Geometry in space
    write_colors : bool
      Write colors or not
    delimiter : None or str
      What to separate columns with

    Returns
    --------------
    export : str
      Pointcloud in XYZ format
    """
    ...

_xyz_loaders = ...
_xyz_exporters = ...
