"""
This type stub file was generated by pyright.
"""

from dm_control.composer.initializers.prop_initializer import PropPlacer
from dm_control.composer.initializers.tcp_initializer import ToolCenterPointInitializer

"""Tools for initializing the states of Composer environments."""
