name: Code Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Download mujoco artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: mujoco_nightly.yml
          workflow_conclusion: success
          name: mujoco_wheel
          path: ${{ github.workspace }}
      - name: Download mjx artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: mujoco_nightly.yml
          workflow_conclusion: success
          name: mjx_wheel
          path: ${{ github.workspace }}
      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          bash ./install.sh -d
          pip install --no-deps --force-reinstall mujoco-*.whl
      - name: Run black
        shell: bash -l {0}
        run: black --check .
      - name: Run flake8
        shell: bash -l {0}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run pyright
        shell: bash -l {0}
        run: |
          pyright
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest