name: Build Nightly MuJoCo Release

on:
  schedule:
    - cron: "0 5 * * *"  # runs at 5AM every day

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Free Up GitHub Actions Ubuntu Runner Disk Space 🔧
        uses: jlumbroso/free-disk-space@main
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false

          # All of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: ambersim
          use-mamba: true
          environment-file: environment.yml
      - name: Create and Store Wheel
        shell: bash -l {0}
        run: |
          # Installs mujoco from source
          run ./install_mj_source.sh
          
          # Store the package as an artifact
          # the below path is known from the mujoco installation script
          whl_path=$(find $PWD/../mujoco/python/dist -name "mujoco-*.whl")
          echo "::set-output name=file_path::$whl_path"
        id: package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.file_path }}
          path: ${{ steps.package.outputs.file_path }}