name: Build Nightly MuJoCo Release

on:
  schedule:
    - cron: "53 4 * * *"  # runs at 4:53AM every day - avoid high load on the hour
  workflow_call:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Free Up GitHub Actions Ubuntu Runner Disk Space 🔧
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false  # might have useful/necessary stuff
          android: true
          dotnet: true
          haskell: true
          large-packages: false  # doesn't save that much space relatively, takes long to run
          swap-storage: true

      # for caching the conda env
      # see: https://github.com/conda-incubator/setup-miniconda#caching-environments
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env
          use-mamba: true
      - name: Cache conda
        uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0
        with:
          path: ${{ env.CONDA }}/envs
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}
        id: cache
      - name: Update environment
        run:
          mamba env update -n ambersim -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      # download previously built mujoco artifact to check version
      - name: Download mujoco artifact
        id: download-artifact-mujoco
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: mujoco_nightly.yml
          workflow_conclusion: success
          check_artifacts: true
          search_artifacts: true
          name_is_regexp: true
          name: "mujoco_wheel-*"
          path: ${{ github.workspace }}

      - name: Build pre-check
        shell: bash -l {0}
        run: |
          # Checks the git hash of the cached files vs. the most recent one
          LATEST_GIT_HASH=$(git ls-remote https://github.com/google-deepmind/mujoco HEAD | awk '{ print $1}')

          filename=$(find ${{ github.workspace }} -type f -name "mujoco_wheel-*.whl" -print -quit)
          echo "[DEBUG] filename: $filename"

          if [ -n "$filename" ]; then
              # if the file name exists, extract the git hash and compare to upstream mujoco
              CACHED_GIT_HASH=$(echo "$filename" | awk -F'mujoco_wheel-' '{print $2}' | awk -F'.' '{print $1}')
              if [ "$LATEST_GIT_HASH" = "$CACHED_GIT_HASH" ]; then
                echo "Cached wheel matches most recent one - skipping build! Hash: $CACHED_GIT_HASH"
                exit 0
              fi
          else
              echo "No cached wheels found - building new ones!"
          fi

      # mujoco build + install
      - name: Create and Store Wheel
        shell: bash -l {0}
        run: |
          # Installs mujoco from source
          sudo apt-get update -y
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxi-dev \
            ninja-build
          python -m pip install --upgrade pip
          ./install_mj_source.sh
          
          # Saving the wheels to respective paths
          mujoco_whl_path=$(find $PWD/../mujoco/python/dist -name "mujoco-*.whl")
          mjx_whl_path=$(find $PWD/../mujoco/mjx -name "mujoco_mjx-*.whl")
          echo "mujoco_path=$(realpath $mujoco_whl_path)" >> $GITHUB_ENV
          echo "mjx_path=$(realpath $mjx_whl_path)" >> $GITHUB_ENV

          # Appending the relevant git commit hash to the artifact name
          LATEST_GIT_HASH=$(git ls-remote https://github.com/google-deepmind/mujoco HEAD | awk '{ print $1}')
          echo "[DEBUG] LATEST_GIT_HASH: $LATEST_GIT_HASH"
          echo "mujoco_name=mujoco_wheel-${LATEST_GIT_HASH}" >> $GITHUB_ENV
          echo "mjx_name=mjx_wheel-${LATEST_GIT_HASH}" >> $GITHUB_ENV
        id: package

      - name: Upload mujoco artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.mujoco_name }}
          path: ${{ env.mujoco_path }}
          retention-days: 7

      - name: Upload mjx artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.mjx_name }}
          path: ${{ env.mjx_path }}
          retention-days: 7